# Generated by Django 6.0.5 on 2026-05-25 16:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_align_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(unique=True)),
                ('stripe_account_id', models.CharField(max_length=255, unique=True)),
                ('onboarding_url', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': "payments_connected_account",
                'indexes': [models.Index(fields=['org_id'], name='idx_connected_account_org')],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField()),
                ('stripe_account_id', models.CharField(max_length=255)),
                ('stripe_transfer_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': "payments_payout",
                'indexes': [models.Index(fields=['org_id', '-created_at'], name='idx_payout_org_created')],
            },
        ),
    ]
