# Generated by Django 6.0.5 on 2026-05-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_add_customer_email_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='registration_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
