# Generated by Django 6.0.5 on 2026-05-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_allow_null_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='organization_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
